export const ghlBookingUrl = process.env.NEXT_PUBLIC_GHL_BOOKING_URL || '/contact';
export const businessPhoneDisplay = '978-915-6499';
export const businessPhoneHref = 'tel:9789156499';
export const ghlFormUrl = process.env.NEXT_PUBLIC_GHL_FORM_URL || '';

export const industryPages = {
  'auto-repair': {
    name: 'Auto Repair',
    eyebrow: 'AI systems for repair shops',
    headline: 'Turn missed calls into booked repair jobs.',
    subhead: 'Essential Solutions helps auto repair shops recover missed calls, answer common customer questions, book appointments, send reminders, and request reviews automatically.',
    image: 'https://images.pexels.com/photos/3807277/pexels-photo-3807277.jpeg?auto=compress&cs=tinysrgb&w=1400',
    pains: ['Missed calls during busy shop hours', 'Customers asking repetitive pricing and availability questions', 'No-shows and forgotten appointments', 'Good customers leaving without a review'],
    outcomes: ['Recover missed-call leads', 'Book more estimates and service appointments', 'Reduce front desk interruptions', 'Build a stronger review profile'],
    workflow: ['Customer calls or texts', 'AI responds or routes the lead', 'Appointment is booked or followed up', 'CRM tracks the opportunity', 'Review request is sent after service'],
  },
  'med-spas': {
    name: 'Med Spas',
    eyebrow: 'AI systems for med spas',
    headline: 'Capture consultations before leads choose another provider.',
    subhead: 'We help med spas respond quickly, book consultations, follow up with undecided leads, and build reputation through automated review requests.',
    image: 'https://images.pexels.com/photos/3997981/pexels-photo-3997981.jpeg?auto=compress&cs=tinysrgb&w=1400',
    pains: ['Leads comparing multiple providers', 'Slow consultation follow-up', 'Front desk overloaded with basic questions', 'Inconsistent review requests'],
    outcomes: ['Faster consultation response', 'More booked appointments', 'Better lead nurturing', 'More reputation-building touchpoints'],
    workflow: ['Lead calls, texts, or fills a form', 'AI answers FAQs and captures interest', 'Calendar booking link is delivered', 'Follow-up continues until booked', 'Review request sent after visit'],
  },
  'dental': {
    name: 'Dental Offices',
    eyebrow: 'AI systems for dental offices',
    headline: 'Keep new patient requests from slipping through the cracks.',
    subhead: 'We help dental offices manage missed calls, new patient inquiries, appointment reminders, review requests, and follow-up through one clean system.',
    image: 'https://images.pexels.com/photos/3845766/pexels-photo-3845766.jpeg?auto=compress&cs=tinysrgb&w=1400',
    pains: ['New patient calls missed during procedures', 'Manual appointment reminders', 'Untracked inquiries', 'Weak review follow-up'],
    outcomes: ['More new patient opportunities captured', 'Fewer no-shows', 'Cleaner patient inquiry tracking', 'More consistent review generation'],
    workflow: ['Inquiry comes in', 'AI captures details', 'Appointment reminder sequence starts', 'Pipeline tracks status', 'Review request sent after visit'],
  },
  'home-services': {
    name: 'Home Services',
    eyebrow: 'AI systems for home service companies',
    headline: 'Answer faster, quote cleaner, and follow up automatically.',
    subhead: 'We help contractors and home service teams capture job requests, screen leads, route urgent calls, and follow up until estimates are booked.',
    image: 'https://images.pexels.com/photos/4792487/pexels-photo-4792487.jpeg?auto=compress&cs=tinysrgb&w=1400',
    pains: ['Calls missed while crews are on jobs', 'Lead details scattered across texts and voicemails', 'Slow estimate follow-up', 'No consistent review process'],
    outcomes: ['More estimate requests captured', 'Better job intake', 'Faster follow-up', 'Cleaner customer pipeline'],
    workflow: ['Job request comes in', 'AI collects basic details', 'Lead is routed or booked', 'Follow-up sequence runs', 'Completed job triggers review request'],
  },
  'logistics': {
    name: 'Logistics',
    eyebrow: 'AI systems for logistics teams',
    headline: 'Organize calls, leads, dispatch requests, and follow-up in one system.',
    subhead: 'We help logistics and transport businesses reduce communication chaos, track customer requests, and automate status updates and follow-up.',
    image: 'https://images.pexels.com/photos/4484149/pexels-photo-4484149.jpeg?auto=compress&cs=tinysrgb&w=1400',
    pains: ['Dispatch calls and customer requests scattered everywhere', 'Missed quote requests', 'Manual updates wasting time', 'No central customer pipeline'],
    outcomes: ['Cleaner request tracking', 'Better customer communication', 'Reduced repetitive updates', 'Stronger follow-up process'],
    workflow: ['Request comes in', 'System captures details', 'Pipeline tracks status', 'Automated updates go out', 'Follow-up/review request triggered'],
  },

  'contractors': {
    name: 'Contractors',
    eyebrow: 'AI systems for local contractors',
    headline: 'Stop losing estimate requests while you are on the job.',
    subhead: 'Essential Solutions helps contractors capture calls, organize estimate requests, follow up with homeowners, and request reviews after completed jobs.',
    image: 'https://images.pexels.com/photos/8961065/pexels-photo-8961065.jpeg?auto=compress&cs=tinysrgb&w=1400',
    pains: ['Calls missed while crews are working', 'Unclear job details from voicemail and text', 'Slow estimate follow-up', 'Happy customers never asked for reviews'],
    outcomes: ['Cleaner job intake', 'Faster quote follow-up', 'More booked estimates', 'Stronger local reputation'],
    workflow: ['Customer requests work', 'System captures job details', 'Estimate is booked or routed', 'Follow-up sequence keeps lead warm', 'Review request sent after completion'],
  },
  'law-offices': {
    name: 'Law Offices',
    eyebrow: 'AI systems for law offices',
    headline: 'Respond to new client inquiries before they call the next firm.',
    subhead: 'We help law offices capture intake requests, route urgent matters, follow up professionally, and keep prospective clients organized in one pipeline.',
    image: 'https://images.pexels.com/photos/5668473/pexels-photo-5668473.jpeg?auto=compress&cs=tinysrgb&w=1400',
    pains: ['New client calls missed during meetings', 'Manual intake follow-up', 'No centralized lead tracking', 'Slow response creates lost opportunities'],
    outcomes: ['Faster inquiry capture', 'Cleaner intake routing', 'Better follow-up discipline', 'More visibility into potential cases'],
    workflow: ['Inquiry comes in', 'System captures basic intake details', 'Lead routed to the right person', 'Follow-up reminders continue', 'Pipeline tracks next action'],
  },
  'cleaning-companies': {
    name: 'Cleaning Companies',
    eyebrow: 'AI systems for cleaning companies',
    headline: 'Book more cleaning jobs without chasing every inquiry manually.',
    subhead: 'Essential Solutions helps cleaning companies respond to quotes, collect details, book appointments, follow up, and request reviews automatically.',
    image: 'https://images.pexels.com/photos/4239146/pexels-photo-4239146.jpeg?auto=compress&cs=tinysrgb&w=1400',
    pains: ['Quote requests left unanswered', 'Manual scheduling back-and-forth', 'No-shows and weak confirmations', 'No repeatable review process'],
    outcomes: ['More quote requests captured', 'Cleaner scheduling', 'Better reminders', 'More reviews from completed jobs'],
    workflow: ['Quote request arrives', 'System collects service details', 'Appointment is booked', 'Reminder sequence runs', 'Review request follows completion'],
  },
};


export const servicePages = {
  'esa-voice': {
    name: 'ESA Voice',
    eyebrow: 'AI voice assistant',
    headline: 'A front desk that answers, qualifies, and routes calls without burning out your team.',
    subhead: 'ESA Voice gives businesses a professional first response when staff are busy, after hours, or already helping customers. It captures the reason for the call, answers approved basic questions, pushes qualified prospects toward booking, and escalates when a human should take over.',
    image: 'https://images.pexels.com/photos/8867433/pexels-photo-8867433.jpeg?auto=compress&cs=tinysrgb&w=1400',
    why: ['Customers judge your business by how fast you respond.', 'Missed calls often become competitors’ customers.', 'Your team should not spend the day repeating basic information.', 'A consistent call flow creates cleaner intake and fewer lost opportunities.'],
    outcomes: ['Answer more calls', 'Capture caller intent', 'Route urgent requests', 'Book or request appointments', 'Reduce repetitive front desk work'],
    process: ['Caller reaches your business', 'ESA greets and identifies the need', 'Approved answers or intake questions are handled', 'Qualified prospects are routed to booking or follow-up', 'Complex calls are escalated to your team'],
  },
  'smart-text-follow-up': {
    name: 'Smart Text Follow-Up',
    eyebrow: 'Lead recovery and nurturing',
    headline: 'Keep leads warm when they do not answer, do not book, or need another touch.',
    subhead: 'Smart text follow-up helps businesses respond quickly, send booking links, remind customers, recover missed calls, and keep conversations moving without relying on memory or sticky notes.',
    image: 'https://images.pexels.com/photos/5053740/pexels-photo-5053740.jpeg?auto=compress&cs=tinysrgb&w=1400',
    why: ['Speed-to-lead matters.', 'Most prospects need more than one touch.', 'Manual follow-up is inconsistent when the day gets busy.', 'Text is fast, direct, and easy for customers to respond to.'],
    outcomes: ['Recover missed-call leads', 'Send reminders automatically', 'Deliver booking links', 'Follow up after quotes', 'Reactivate older contacts'],
    process: ['Lead calls, texts, or submits a form', 'System sends the right response', 'Prospect gets a clear next step', 'Reminders continue when needed', 'Conversation gets tracked in one place'],
  },
  'crm-pipeline-tracking': {
    name: 'CRM & Pipeline Tracking',
    eyebrow: 'Visibility and control',
    headline: 'Know where every lead stands instead of guessing from texts, voicemails, and notebooks.',
    subhead: 'We structure a clean lead pipeline so owners and teams can see who called, who booked, who needs follow-up, and where revenue is being lost.',
    image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1400',
    why: ['Scattered lead information causes missed money.', 'Owners need visibility without micromanaging.', 'Sales and service teams need clear next steps.', 'Better tracking makes better decisions possible.'],
    outcomes: ['Organized contacts', 'Clear pipeline stages', 'Lead source visibility', 'Follow-up reminders', 'Better team accountability'],
    process: ['Lead enters the system', 'Contact record is created', 'Opportunity moves through pipeline stages', 'Follow-up tasks and messages are triggered', 'Owner can review activity and outcomes'],
  },
  'appointment-booking': {
    name: 'Appointment Booking',
    eyebrow: 'Scheduling automation',
    headline: 'Make it easier for customers to book and harder for appointments to fall apart.',
    subhead: 'Appointment booking systems reduce back-and-forth, send confirmations, support reminders, and help your team keep the calendar cleaner.',
    image: 'https://images.pexels.com/photos/5716001/pexels-photo-5716001.jpeg?auto=compress&cs=tinysrgb&w=1400',
    why: ['Customers want simple scheduling.', 'No-shows waste time.', 'Staff lose hours coordinating appointments manually.', 'A cleaner booking flow makes the business feel more professional.'],
    outcomes: ['Online booking', 'Calendar coordination', 'Confirmation messages', 'Reminder sequences', 'Easier rescheduling'],
    process: ['Customer requests time', 'Available options are offered', 'Appointment is confirmed', 'Reminders are sent', 'Status is tracked in the CRM'],
  },
  'review-growth': {
    name: 'Review Growth',
    eyebrow: 'Reputation support',
    headline: 'Turn satisfied customers into visible proof that helps the next customer trust you.',
    subhead: 'Review growth workflows help businesses ask at the right time, route happy customers toward reviews, and build a stronger reputation without awkward manual chasing.',
    image: 'https://images.pexels.com/photos/3183153/pexels-photo-3183153.jpeg?auto=compress&cs=tinysrgb&w=1400',
    why: ['Reviews influence buying decisions.', 'Happy customers often forget unless asked.', 'Consistent review requests build trust over time.', 'A stronger reputation can improve conversion before a sales conversation even starts.'],
    outcomes: ['Automated review requests', 'Better timing', 'More customer feedback', 'Improved local trust', 'Reputation visibility'],
    process: ['Service is completed', 'Customer receives a review request', 'Positive experiences are guided to public review', 'Feedback is captured', 'Reputation improves over time'],
  },
  'automation-workflows': {
    name: 'Automation Workflows',
    eyebrow: 'Operational efficiency',
    headline: 'Automate repetitive follow-up so your team can focus on the work that actually needs them.',
    subhead: 'Automation workflows connect calls, forms, texts, calendars, reviews, internal notifications, and follow-up into one repeatable system.',
    image: 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1400',
    why: ['Repetitive admin work drains teams.', 'Manual processes break when business gets busy.', 'Consistency improves customer experience.', 'Automation creates scale without immediately adding staff.'],
    outcomes: ['Lead nurture sequences', 'Internal alerts', 'Appointment reminders', 'Reactivation campaigns', 'Consistent follow-up'],
    process: ['Trigger happens', 'System identifies the right path', 'Messages, tasks, or updates are sent', 'Lead status changes automatically', 'Team steps in when needed'],
  },
};

export const faqs = [
  ['Is this just software access?', 'No. The offer is implementation. We install the CRM, automations, AI workflows, booking process, and follow-up system so the business can actually use it.'],
  ['Do I need to replace my staff?', 'No. The goal is to reduce repetitive admin work and help your team respond faster, not remove the human side of the business.'],
  ['Can this work with my current website?', 'Yes. We can connect forms, booking links, chat widgets, tracking, and follow-up systems to your existing site.'],
  ['What happens after launch?', 'We monitor the system, review performance, adjust workflows, and help improve the process over time depending on your package.'],
];
